# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path0 test

name: Maven Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Server
      #uses: easingthemes/ssh-deploy@v2.1.5
      uses: burnett01/rsync-deployments@4.1
      env:
          
          switches: -avzr --delete
          path: jenkins/
          remote_path: /home/ubuntu/testdeploy
          remote_user: root
          remote_host: 149.81.166.9
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
          
          
